# Utilizar una imagen base de Node.js
FROM node:16

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo package.json y package-lock.json al contenedor
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar todo el código fuente al contenedor
COPY . .

# Exponer el puerto especificado en el archivo .env
EXPOSE 3002

# Iniciar el microservicio
CMD ["npm", "start"]