# Usa la imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos necesarios
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del microservicio
COPY . .

# Expone el puerto en el que corre tu aplicación (según tu microservicio, suele ser 3000)
EXPOSE 3000

# Comando por defecto para ejecutar la app
CMD ["npm", "start"]